### ISSUE TITLE
Need NCBI IDs for new curation

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/bugphyzz#103]
I added 90,000 some waste water annotations in habitat in MetaPlan naming structure. And also I added a new health associated physiology from one of Levi's papers. Both will need IDs

**Comment by sdgamboa** [comment]
@JonathanYe3 

+ Getting NCBI IDs and taxon name missing for this dataset (with accession ID): 

```
$ efetch -db sra -id ERR2221148 -format docsum | xtract -pattern DocumentSummary -element Sample@acc Organism@taxid Organism@ScientificName
ERS417248	160404	Anaerotignum lactatifermentans
```

+ MiDAs IDs

k__Bacteria; p__Bacteroidota; c__Bacteroidia; o__Bacteroidales; f__Dysgonomonadaceae; g__Proteiniphilum; s__midas_s_445.

Would become

Taxon_name: "unknown"
NCBI_ID: "unknown"
Rank: "strain" ?? I think that's why it has a double s? @kbeckenrode 

Parent_name: "Proteiniphilum"
Parent_rank: "genus"
Parent_ID: "294702"
MIDAS_ID: "445" # this wold be an additional column which would be optional in the template. Make sure to add the regex to the template file.

**Comment by JonathanYe3** [comment]
On it

**Comment by JonathanYe3** [comment]
Oh awesome, this will be super helpful! I hardly have experience using command line, so I would much rather go this route.
