### ISSUE TITLE
`plant pathogenicity`

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/bugphyzz#104]
Document what `plant pathogenicity = FALSE` means and how this differs from no information. Try to find a citation for some of these data.

**Comment by sdgamboa** [comment]
Physiologies like plant pathogenicity in which FALSE could have meaning (rather than missing values) are treated as binary attributes, for example, `plant pathogenicity--TRUE` and `plant pathogenicity--FALSE`. I couldn't report back the citation because I couldn't find it again (they changed their page). However, these FALSE values were the result of an assay.
