### ISSUE TITLE
Data issues?

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/bugphyzz#178]
While looking at the data to determine how we should group for signatures, I noticed a few things:

* In antimicrobial resistence, I noticed some variation in the attribute column. Most entries say 'resistance to X', where X is some cefepime or ciprofloxacin for example, but there are a few that I thought they could be reworded, such as "not resistant to beta-lactam". Should this be "resistance to beta-lactam" with attribute_value = FALSE? Also, there are entries for "carbapenem-resistant Acinetobacter". Should this be "resistance to carbapenem"?
* In disease association,  I noticed Bacillus cellulosilyticus DSM 2522 has an attribute value of 'no'--is that correct?

**Comment by sdgamboa** [comment]
+ Would `"resistance to beta-lactam" with attribute_value = FALSE` mean the same as `sensitive to beta-lactam" with attribute_value = TRUE`? I think all values are TRUE in the antimicrobial resistance datataset.

+ I think "resistant to carbapenem" would the right term in the case of Acinetobacter. Probably all `resistance` should be changed to `resistant`?. I think an adjective could be better in this case (since we have "sensitive" and not "sensitivity" in the other rows).

``` r
suppressMessages({
    library(bugphyzz)
    library(dplyr)
    library(stringr)
    res <- physiologies('antimicrobial resistance')[[1]]
})
attr <- unique(pull(res, Attribute))
table(unlist(lapply(attr, function(x) str_extract_all(x, "(res\\w+|sen\\w+)"))))
#> 
#> resistance  resistant  sensitive 
#>         26          3         25
table(res$Attribute_value)
#> 
#>  TRUE 
#> 10311
```

<sup>Created on 2022-09-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sdgamboa** [comment]
@kbeckenrode, any thoughts about this discussion?

**Comment by lwaldron** [comment]
What's the status of this stale issue?

**Comment by sdgamboa** [comment]
In regards to antimicrobial resistance, the attributes have been checked and added to the valid attributes ([here](https://github.com/waldronlab/bugphyzz/blob/devel/inst/extdata/attributes.tsv#L46)). All values are TRUE.

I don't see the value 'no' anymore for Bacillus cellulosilyticus DSM 2522 in disease association: https://docs.google.com/spreadsheets/d/1MAtkI-UEc7T33BYvLBAkw4PDmEmNBroMVUi4KwN8cCc/edit#gid=546928968

So, I think this issue could be closed?
