### ISSUE TITLE
Add units to signature names created with range or numeric attributes

### ISSUE THREAD

**Issue by sdgamboa** [waldronlab/bugphyzz#199]
- [ ] Add units to signatures names created with ranges and numbers.
- [ ] Add units to the names of the physiologies in showPhys.
- [ ] Add names for range signatures, when the range falls within a defined threshold. (This might also be an argument, maybe?)

**Comment by jwokaty** [comment]
Could I also add that a signature can take a name? So that I can use the threshold names that @kbeckenrode provided in https://docs.google.com/spreadsheets/d/1MM7unEZzwfjllFGzFScV9T1gAQxBXbu03ZmozGczKIw/edit#gid=0?

For example, 

```
bugphyzz:acetate producing| small -10.6-0.7	NA	105832	105833	411483	105840	105831	360807	105843	105829	105834	105825	105839	136624	105830
bugphyzz:acetate producing|medium 0.71-7.2	NA	105826	105842	105838	105845									
bugphyzz:acetate producing|large 7.21-47.9	NA	105844	105835	105837										
```
It's not clear to me how someone might use this .gmt file, but if they want to search the data, it's easier to search for something like `acetate*small`. If it's easy to get this information in R another way or you think users won't use it this way, it's fine not to use this.

**Comment by sdgamboa** [comment]
@jwokaty, yes. Definitely, a name such as small or thermophile, etc. would be more useful for end-users, I think.
