### ISSUE TITLE
Syntax correct on curation page won't go to next page

### ISSUE THREAD

**Issue by kbeckenrode** [waldronlab/bugphyzz#209]
[The curation check page](https://waldronlab.io/bugphyzz/articles/checks.html) has a section called syntax/values and I'd like to go to the next page, but it won't print. Or perhaps we can mark disease association accounted for because we decided not to do ontology terms for these.

Either way is fine with me.

**Comment by sdgamboa** [comment]
I think the purpose of the [attributes.tsv](https://github.com/waldronlab/bugphyzz/blob/main/inst/extdata/attributes.tsv) file is two-fold:

1) Ensuring that only valid attribute values are used in each spreadsheet. So we need to add all attributes and attribute values, even those without ontology.
2) Registering the ontology terms (which I assume will be added to the dataset?).

So I think that the attributes here still need to be added to the attributes.tsv file in order to perform the checks.

@kbeckenrode, are you doing some kind of validation of these terms? or are all of them correct already? If so, I can just add all of them to the attributes.tsv file and fill all of the other columns with NA.

On another note, I see a few taxa annotated with multiple diseases in a single cell, e.g., 'bacteremia, endocarditis, urinary tract infection'. Should these be divided into several rows? one for each of the terms separated by a comma?

**Comment by kbeckenrode** [comment]
@sdgamboa Ah yes yes, thank you for reminding me. I thought they were entered to attributes, but I think not. I'll take care it and let know if I have any problems
